### ISSUE TITLE
Update the Dockerfile to support live reloading for the python app

### ISSUE THREAD

**Issue by KevinGreene** [kcards/kcards#138]

**Comment by jacebrowning** [comment]
If we go with another framework for the frontend, the existing `Dockerfile` should be sufficient to reload the API when any Python code changes.

**Comment by KevinGreene** [comment]
I don't believe it is. At the very least, we need to modify this - https://github.com/kcards/kcards/blob/master/Dockerfile#L8 - to be a volume mount. Otherwise each time code is changed, you'd have to rebuild the Dockerfile.

The existing Dockerfile is how it would look in production, but in dev we should probably just add the entire directory as a mounted volume, and on start run a script that includes `pip install`

**Comment by jacebrowning** [comment]
Any reason you wouldn't use a mounted volume in production?

**Comment by KevinGreene** [comment]
Main reason being that it goes against some principles of Docker, and essentially makes the image worthless.

Docker images in production should generally be runnable without much setup. There are always exceptions, but it should be quick to start, static, and mostly self-contained.

By using volumes in production, we'd

1) Signal that production code could change at any given time, otherwise there'd be no reason to use volumes
2) Shift time from building the image to starting the image (pip install would run on `docker run`, not `docker build`
3) Greatly increase the amount of infrastructure and ops required to support this (You'd have to have volume mounts that pull down the code on launch, essentially, requiring a kind of goofy and big setup).

Put another way,

> Data volumes are designed to persist data, independent of the container’s lifecycle.

That's not really what we want to do with code.

**Comment by KevinGreene** [comment]
Turns out we can just mount the working directory over the volume via `docker-compose`. I thought this wasn't possible, but apparently I misremembered.

**Comment by jacebrowning** [comment]
Nice! I'm needed something like this for work.
