### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by jacebrowning** [kcards/kcards#17]
This will be used for:
- GitHub organization
- Site favicon
- Application shortcuts

**Comment by DanLindeman** [comment]
Would love to use something similar to the Kotlin K, but maybe Red/Yellow/Green (https://avatars2.githubusercontent.com/u/1446536?v=3&s=400)

**Comment by jacebrowning** [comment]
What if the right side of the `K` is curved to look like the left side of a `C`?

**Comment by DanLindeman** [comment]
Also was thinking about maybe like a hand holding a card up (like a Soccer/Football Red/Yellow Card)

**Comment by jacebrowning** [comment]
![](https://media.giphy.com/media/Fzbrbag2oHzmU/giphy.gif)

**Comment by jacebrowning** [comment]
![](http://i.giphy.com/Fzbrbag2oHzmU.gif)
