### ISSUE TITLE
Fix coveralls badge

### ISSUE THREAD

**Issue by jacebrowning** [kcards/kcards#28]
I can't seem to find the project on https://coveralls.io/repos/new. Maybe @DanLindeman needs to activate it?

**Comment by DanLindeman** [comment]
I needed to reauthorize? Weird.
![image](https://cloud.githubusercontent.com/assets/6757569/19712606/428dd074-9b0d-11e6-80c9-35a5461a0bc2.png)

**Comment by DanLindeman** [comment]
Also fixed some settings. This is back up
