### ISSUE TITLE
Should we support blue/purple card?

### ISSUE THREAD

**Issue by jacebrowning** [kcards/kcards#39]
> Blue (or purple): I feel this discussion is becoming (or has become) a rat hole. – This one is not used at larger conferences.

**Comment by jacebrowning** [comment]
I'm sure how this would apply to **automatic** moderation.

**Comment by DanLindeman** [comment]
We'd need like...some sort of domain-specific configuration or something.

**Comment by jacebrowning** [comment]
I'm thinking we should close this until we know what this feature request actually is.

**Comment by DanLindeman** [comment]
Closing along with other custom color issues
