### ISSUE TITLE
Disallow spaces in room codes

### ISSUE THREAD

**Issue by jacebrowning** [kcards/kcards#51]

**Comment by DanLindeman** [comment]
I think we want rooms to have spaces in them though

**Comment by jacebrowning** [comment]
I think we should treat spaces and dashes as the same character for room identification, so if I type "my room" into the box, I'm taken to https://kcards.online/rooms/my-room. Thoughts?

**Comment by DanLindeman** [comment]
Might want to do anything we don't like as a dash then, right? `Dan's super discussion` -> `dan-s-super-discussion`?
