### ISSUE TITLE
Should we use memorable generated room names?

### ISSUE THREAD

**Issue by jacebrowning** [kcards/kcards#59]
Using something like https://github.com/Atrox/haikunatorpy.

**Comment by DanLindeman** [comment]
Not a must-have for me, but it does give a sense of professionalism since popular things like gfycat, heroku, among others do this.

**Comment by jacebrowning** [comment]
My thinking is that they might be easier to to type. I think we should observe some people trying to use the app to gain usability insights.

**Comment by DanLindeman** [comment]
Could be fun too, better license: https://github.com/treyhunner/names/tree/f99542dc21f48aa82da4406f8ce408e92639430d

**Comment by jacebrowning** [comment]
Closed by #77.
