### ISSUE TITLE
Generated Room Names can be too complex

### ISSUE THREAD

**Issue by DanLindeman** [kcards/kcards#80]
`loran-boatswains-dependencies`, while memorable, is not very simple or easy to say/share with people. Unfortunately, there is no "Vocabulary level" option when selecting words. Maybe only let RandomWords choose words that are six characters or less.

**Comment by jacebrowning** [comment]
FYI, if you put "Fixes #80" in the PR description, this would have closed automatically.

https://github.com/blog/1506-closing-issues-via-pull-requests
